services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  initialization-script:
    depends_on:
      - dynamodb-local
    container_name: initialization-script
    build:
      context: ./scripts
      dockerfile: Dockerfile
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - NOTEPAD_TABLE_NAME=my-notepad-dev
    entrypoint: [ "npm", "run", "initialize-dynamodb" ]
